/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author chris
 */
public class intefaz extends javax.swing.JFrame {

    /**
     * Creates new form intefaz
     */
    public intefaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CartaStarTrek = new javax.swing.JLabel();
        CartaStarWars = new javax.swing.JLabel();
        strength = new javax.swing.JLabel();
        agility = new javax.swing.JLabel();
        PS = new javax.swing.JLabel();
        habilities = new javax.swing.JLabel();
        strength1 = new javax.swing.JLabel();
        habilities1 = new javax.swing.JLabel();
        agility1 = new javax.swing.JLabel();
        PS1 = new javax.swing.JLabel();
        strengthpointsST = new javax.swing.JLabel();
        strengthpointsSW = new javax.swing.JLabel();
        pspointsST = new javax.swing.JLabel();
        agilitypointsSW = new javax.swing.JLabel();
        agilitypointsST = new javax.swing.JLabel();
        shpointsSW = new javax.swing.JLabel();
        shpointsST = new javax.swing.JLabel();
        pspointsSW = new javax.swing.JLabel();
        nameSW = new javax.swing.JLabel();
        nameST = new javax.swing.JLabel();
        q1SW = new javax.swing.JLabel();
        q2SW = new javax.swing.JLabel();
        q3SW = new javax.swing.JLabel();
        q4SW = new javax.swing.JLabel();
        q1ST = new javax.swing.JLabel();
        q2ST = new javax.swing.JLabel();
        q3ST = new javax.swing.JLabel();
        q4ST = new javax.swing.JLabel();
        startbattle = new javax.swing.JButton();
        q4SW1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartaStarTrek.setBackground(new java.awt.Color(204, 102, 0));
        CartaStarTrek.setForeground(new java.awt.Color(255, 255, 255));
        CartaStarTrek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaStarTrek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Star_Trek_Customizable_Card_Game_cardback.jpg"))); // NOI18N
        CartaStarTrek.setMaximumSize(new java.awt.Dimension(220, 300));
        CartaStarTrek.setMinimumSize(new java.awt.Dimension(220, 300));
        CartaStarTrek.setOpaque(true);
        CartaStarTrek.setPreferredSize(new java.awt.Dimension(220, 300));
        jPanel2.add(CartaStarTrek, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 230, 320));

        CartaStarWars.setBackground(new java.awt.Color(0, 51, 102));
        CartaStarWars.setForeground(new java.awt.Color(255, 255, 255));
        CartaStarWars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaStarWars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/file.png"))); // NOI18N
        CartaStarWars.setMaximumSize(new java.awt.Dimension(220, 300));
        CartaStarWars.setMinimumSize(new java.awt.Dimension(220, 300));
        CartaStarWars.setOpaque(true);
        CartaStarWars.setPreferredSize(new java.awt.Dimension(220, 300));
        jPanel2.add(CartaStarWars, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 320));

        strength.setBackground(new java.awt.Color(168, 89, 49));
        strength.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        strength.setForeground(new java.awt.Color(255, 255, 255));
        strength.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strength.setText("STRENGTH");
        strength.setToolTipText("xfcvgdsfgdfgdf");
        strength.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        strength.setOpaque(true);
        jPanel2.add(strength, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 180, 30));

        agility.setBackground(new java.awt.Color(0, 153, 153));
        agility.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agility.setForeground(new java.awt.Color(255, 255, 255));
        agility.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agility.setText("AGILITY");
        agility.setToolTipText("xfcvgdsfgdfgdf");
        agility.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agility.setOpaque(true);
        jPanel2.add(agility, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 180, 30));

        PS.setBackground(new java.awt.Color(204, 153, 0));
        PS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PS.setForeground(new java.awt.Color(255, 255, 255));
        PS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PS.setText("SPECIAL HABILITY");
        PS.setToolTipText("xfcvgdsfgdfgdf");
        PS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PS.setOpaque(true);
        jPanel2.add(PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 180, 30));

        habilities.setBackground(new java.awt.Color(0, 153, 0));
        habilities.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        habilities.setForeground(new java.awt.Color(255, 255, 255));
        habilities.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habilities.setText("HEALTH POINTS");
        habilities.setToolTipText("xfcvgdsfgdfgdf");
        habilities.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        habilities.setOpaque(true);
        jPanel2.add(habilities, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, 30));

        strength1.setBackground(new java.awt.Color(51, 102, 255));
        strength1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        strength1.setForeground(new java.awt.Color(255, 255, 255));
        strength1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strength1.setText("STRENGTH");
        strength1.setToolTipText("xfcvgdsfgdfgdf");
        strength1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        strength1.setOpaque(true);
        jPanel2.add(strength1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 180, 30));

        habilities1.setBackground(new java.awt.Color(255, 102, 0));
        habilities1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        habilities1.setForeground(new java.awt.Color(255, 255, 255));
        habilities1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        habilities1.setText("HEALTH POINTS");
        habilities1.setToolTipText("xfcvgdsfgdfgdf");
        habilities1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        habilities1.setOpaque(true);
        jPanel2.add(habilities1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 180, 30));

        agility1.setBackground(new java.awt.Color(255, 0, 0));
        agility1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agility1.setForeground(new java.awt.Color(255, 255, 255));
        agility1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agility1.setText("AGILITY");
        agility1.setToolTipText("xfcvgdsfgdfgdf");
        agility1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agility1.setOpaque(true);
        jPanel2.add(agility1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 180, 30));

        PS1.setBackground(new java.awt.Color(102, 102, 102));
        PS1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PS1.setForeground(new java.awt.Color(255, 255, 255));
        PS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PS1.setText("SPECIAL HABILITY");
        PS1.setToolTipText("xfcvgdsfgdfgdf");
        PS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PS1.setOpaque(true);
        jPanel2.add(PS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 180, 30));

        strengthpointsST.setBackground(new java.awt.Color(51, 102, 255));
        strengthpointsST.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        strengthpointsST.setForeground(new java.awt.Color(255, 255, 255));
        strengthpointsST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthpointsST.setToolTipText("xfcvgdsfgdfgdf");
        strengthpointsST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        strengthpointsST.setOpaque(true);
        jPanel2.add(strengthpointsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 40, 30));

        strengthpointsSW.setBackground(new java.awt.Color(168, 89, 49));
        strengthpointsSW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        strengthpointsSW.setForeground(new java.awt.Color(255, 255, 255));
        strengthpointsSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthpointsSW.setToolTipText("xfcvgdsfgdfgdf");
        strengthpointsSW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        strengthpointsSW.setOpaque(true);
        jPanel2.add(strengthpointsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 40, 30));

        pspointsST.setBackground(new java.awt.Color(255, 102, 0));
        pspointsST.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pspointsST.setForeground(new java.awt.Color(255, 255, 255));
        pspointsST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pspointsST.setToolTipText("xfcvgdsfgdfgdf");
        pspointsST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pspointsST.setOpaque(true);
        jPanel2.add(pspointsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 40, 30));

        agilitypointsSW.setBackground(new java.awt.Color(0, 153, 153));
        agilitypointsSW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agilitypointsSW.setForeground(new java.awt.Color(255, 255, 255));
        agilitypointsSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilitypointsSW.setToolTipText("xfcvgdsfgdfgdf");
        agilitypointsSW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agilitypointsSW.setOpaque(true);
        jPanel2.add(agilitypointsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 40, 30));

        agilitypointsST.setBackground(new java.awt.Color(255, 0, 0));
        agilitypointsST.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agilitypointsST.setForeground(new java.awt.Color(255, 255, 255));
        agilitypointsST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilitypointsST.setToolTipText("xfcvgdsfgdfgdf");
        agilitypointsST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agilitypointsST.setOpaque(true);
        jPanel2.add(agilitypointsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 40, 30));

        shpointsSW.setBackground(new java.awt.Color(204, 153, 0));
        shpointsSW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        shpointsSW.setForeground(new java.awt.Color(255, 255, 255));
        shpointsSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shpointsSW.setToolTipText("xfcvgdsfgdfgdf");
        shpointsSW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shpointsSW.setOpaque(true);
        jPanel2.add(shpointsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 40, 30));

        shpointsST.setBackground(new java.awt.Color(102, 102, 102));
        shpointsST.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        shpointsST.setForeground(new java.awt.Color(255, 255, 255));
        shpointsST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shpointsST.setToolTipText("xfcvgdsfgdfgdf");
        shpointsST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shpointsST.setOpaque(true);
        jPanel2.add(shpointsST, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 40, 30));

        pspointsSW.setBackground(new java.awt.Color(0, 153, 0));
        pspointsSW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pspointsSW.setForeground(new java.awt.Color(255, 255, 255));
        pspointsSW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pspointsSW.setToolTipText("xfcvgdsfgdfgdf");
        pspointsSW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pspointsSW.setOpaque(true);
        jPanel2.add(pspointsSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 40, 30));

        nameSW.setBackground(new java.awt.Color(0, 51, 102));
        nameSW.setOpaque(true);
        jPanel2.add(nameSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 190, 40));

        nameST.setBackground(new java.awt.Color(204, 102, 0));
        nameST.setOpaque(true);
        jPanel2.add(nameST, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 360, 190, 40));

        q1SW.setBackground(new java.awt.Color(0, 51, 102));
        q1SW.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q1SW.setText("     Queue 1:");
        q1SW.setOpaque(true);
        jPanel2.add(q1SW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 460, 30));

        q2SW.setBackground(new java.awt.Color(0, 51, 102));
        q2SW.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q2SW.setText("     Queue 2:");
        q2SW.setOpaque(true);
        jPanel2.add(q2SW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 460, 30));

        q3SW.setBackground(new java.awt.Color(0, 51, 102));
        q3SW.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q3SW.setText("     Queue 3:");
        q3SW.setOpaque(true);
        jPanel2.add(q3SW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 460, 30));

        q4SW.setBackground(new java.awt.Color(0, 51, 102));
        q4SW.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q4SW.setText("     Reforce Queue:");
        q4SW.setOpaque(true);
        jPanel2.add(q4SW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 460, 30));

        q1ST.setBackground(new java.awt.Color(204, 102, 0));
        q1ST.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q1ST.setText("     Queue 1:");
        q1ST.setOpaque(true);
        jPanel2.add(q1ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 460, 30));

        q2ST.setBackground(new java.awt.Color(204, 102, 0));
        q2ST.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q2ST.setText("     Queue 2:");
        q2ST.setOpaque(true);
        jPanel2.add(q2ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 460, 30));

        q3ST.setBackground(new java.awt.Color(204, 102, 0));
        q3ST.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q3ST.setText("     Queue 3:");
        q3ST.setOpaque(true);
        jPanel2.add(q3ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 460, 30));

        q4ST.setBackground(new java.awt.Color(204, 102, 0));
        q4ST.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        q4ST.setText("     Reforce Queue:");
        q4ST.setOpaque(true);
        jPanel2.add(q4ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 460, 30));

        startbattle.setBackground(new java.awt.Color(204, 0, 51));
        startbattle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        startbattle.setText("START BATTLE");
        jPanel2.add(startbattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 350, 70));

        q4SW1.setBackground(new java.awt.Color(204, 0, 51));
        q4SW1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        q4SW1.setText(" BATTLE SPEED:");
        q4SW1.setOpaque(true);
        jPanel2.add(q4SW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 350, 40));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondo.png"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intefaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intefaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CartaStarTrek;
    private javax.swing.JLabel CartaStarWars;
    private javax.swing.JLabel PS;
    private javax.swing.JLabel PS1;
    private javax.swing.JLabel agility;
    private javax.swing.JLabel agility1;
    private javax.swing.JLabel agilitypointsST;
    private javax.swing.JLabel agilitypointsSW;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel habilities;
    private javax.swing.JLabel habilities1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameST;
    private javax.swing.JLabel nameSW;
    private javax.swing.JLabel pspointsST;
    private javax.swing.JLabel pspointsSW;
    private javax.swing.JLabel q1ST;
    private javax.swing.JLabel q1SW;
    private javax.swing.JLabel q2ST;
    private javax.swing.JLabel q2SW;
    private javax.swing.JLabel q3ST;
    private javax.swing.JLabel q3SW;
    private javax.swing.JLabel q4ST;
    private javax.swing.JLabel q4SW;
    private javax.swing.JLabel q4SW1;
    private javax.swing.JLabel shpointsST;
    private javax.swing.JLabel shpointsSW;
    private javax.swing.JButton startbattle;
    private javax.swing.JLabel strength;
    private javax.swing.JLabel strength1;
    private javax.swing.JLabel strengthpointsST;
    private javax.swing.JLabel strengthpointsSW;
    // End of variables declaration//GEN-END:variables
}
